# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: ns-vs-demo
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /microservice1
        pathType: Prefix
        backend:
          service:
            name: microservice1-svc
            port:
              number: 80
