# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: ns-vs-demo
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: gce
  rules:
  - http:
      paths:
      - path: /microservice1/greet
        pathType: Prefix
        backend:
          service:
            name: microservice1-svc
            port:
              number: 80
