# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: ns-vs-demo
  annotations:
    kubernetes.io/ingress.class: "gce"  # For GCP Ingress
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /microservice1
        pathType: Prefix
        backend:
          service:
            name: microservice1
            port:
              number: 80
      - path: /microservice2
        pathType: Prefix
        backend:
          service:
            name: microservice2
            port:
              number: 80
      - path: /microservice3
        pathType: Prefix
        backend:
          service:
            name: microservice3
            port:
              number: 80
