# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: ns-vs-demo
  annotations:
    kubernetes.io/ingress.class: "gce"  # For GCP Ingress
spec:
  rules:
  - http:
      paths:
      - path: /microservice1/greet
        pathType: Prefix
        backend:
          service:
            name: microservice1
            port:
              number: 80
