apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3
  namespace: ns-vs-demo
  labels:
    app: microservice3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice3
  template:
    metadata:
      labels:
        app: microservice3
    spec:
      containers:
      - name: microservice3
        image: testcicdvs.jfrog.io/vs-docker-repo/microservice3:3.1.0
        ports:
        - containerPort: 8083
      imagePullSecrets:
      - name: regcred

# microservice3-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice3
  namespace: ns-vs-demo
spec:
  selector:
    app: microservice3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083