apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  namespace: ns-vs-demo
  labels:
    app: microservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: testcicdvs.jfrog.io/vs-docker-repo/microservice2:3.1.0
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: regcred

# microservice2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: ns-vs-demo
spec:
  selector:
    app: microservice2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082