# microservice2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: ns-vs-demo
spec:
  selector:
    app: microservice2
  ports:
  - protocol: http
    port: 80
    targetPort: 8082