# microservice3-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice3
  namespace: ns-vs-demo
spec:
  selector:
    app: microservice3
  ports:
  - protocol: http
    port: 80
    targetPort: 8083