apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: ns-vs-demo
  labels:
    app: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: testcicdvs.jfrog.io/vs-docker-repo/microservice1:3.1.0
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: regcred

# microservice1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice1
  namespace: ns-vs-demo
spec:
  selector:
    app: microservice1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
