name: Create or Update GKE Cluster

on:
  workflow_dispatch: # Manual trigger

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Step 2: Create or update the GKE Cluster
    - name: Create or Update GKE Cluster
      run: |
        set -e
        echo "Checking if GKE cluster exists..."
        if ! gcloud container clusters describe ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GCP_REGION }} >/dev/null 2>&1; then
          echo "Cluster not found. Creating GKE cluster..."
          gcloud container clusters create ${{ secrets.GKE_CLUSTER }} \
            --region ${{ secrets.GCP_REGION }} \
            --num-nodes 3 \
            --machine-type e2-medium \
            --enable-ip-alias \
            --release-channel regular
        else
          echo "Cluster already exists. Skipping creation."
        fi
