name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARTIFACTORY_URL: testcicdvs.jfrog.io
      RELEASE_VERSION: 3.1.0
      ARTIFACTORY_REPO: vs-docker-repo
      GKE_PROJECT: your-gcp-project-id
      GKE_CLUSTER: your-gke-cluster-name
      GKE_ZONE: your-gke-cluster-zone
      DOCKER_REGISTRY: ${{ secrets.ARTIFACTORY_DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      GCP_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Java for Maven builds
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build and Deploay the microservices using Maven
    - name: Build and Deploy with Maven
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: mvn clean deploy -DskipTests -s ./settings.xml

    # Log in to Artifactory Docker registry
    - name: Docker Login to Artifactory
      run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # Build Docker images for each microservice
    - name: Build Docker Images
      run: |
        docker build -t $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice1:$RELEASE_VERSION ./microservice1
        docker build -t $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice2:$RELEASE_VERSION ./microservice2
        docker build -t $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice3:$RELEASE_VERSION ./microservice3

    # Push Docker images to Artifactory
    - name: Push Docker Images to Artifactory
      run: |
        docker push $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice1:$RELEASE_VERSION
        docker push $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice2:$RELEASE_VERSION
        docker push $ARTIFACTORY_URL/$ARTIFACTORY_REPO/microservice3:$RELEASE_VERSION

    # Set up Google Cloud SDK
    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        credentials_json: $GCP_CREDENTIALS

    # Authenticate with GKE
    - name: Authenticate with GKE
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT

    # Deploy microservices to GKE
    - name: Deploy to GKE
      run: |
        kubectl apply -f ./k8s/microservice1-deployment.yaml
        kubectl apply -f ./k8s/microservice2-deployment.yaml
        kubectl apply -f ./k8s/microservice3-deployment.yaml
