name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure gke-gcloud-auth-plugin
        run: echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "Cluster: ${{ secrets.GKE_CLUSTER }}"
          echo "Zone: ${{ secrets.GCP_REGION }}"
          echo "Project: ${{ secrets.GKE_PROJECT }}"

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GKE_PROJECT }}

      - name: Deploy microservices
        run: |
          kubectl apply -f ./k8s/microservice1-deployment.yaml
          kubectl apply -f ./k8s/microservice2-deployment.yaml
          kubectl apply -f ./k8s/microservice3-deployment.yaml